import React, { useState, useEffect } from 'react';
import { User, Shop } from '../types';
import MobileSelect from './MobileSelect';

interface UserModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSave: (userData: (Omit<User, 'role' | 'isActive'> & { password?: string }) | User) => void;
    userToEdit: User | null;
    allUsers: User[];
    shops: Shop[];
    isLoading?: boolean;
}

const UserModal: React.FC<UserModalProps> = ({ isOpen, onClose, onSave, userToEdit, allUsers, shops, isLoading = false }) => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [shopId, setShopId] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [error, setError] = useState('');

    useEffect(() => {
        if (!isOpen) return;

        setError('');
        if (userToEdit) {
            setName(userToEdit.name);
            setEmail(userToEdit.email);
            setShopId(userToEdit.shopId || '');
            setPassword('');
            setConfirmPassword('');
        } else {
            setName('');
            setEmail('');
            setShopId(shops[0]?.id || '');
            setPassword('');
            setConfirmPassword('');
        }
    }, [userToEdit, isOpen, shops]);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setError('');

        if (!name.trim() || !email.trim() || !shopId) {
            setError('الرجاء ملء جميع الحقول المطلوبة.');
            return;
        }

        if (!userToEdit) {
            if (!password.trim()) {
                setError('كلمة المرور مطلوبة للمستخدم الجديد.');
                return;
            }
            if (password.length < 6) {
                setError('كلمة المرور يجب أن تكون 6 أحرف على الأقل.');
                return;
            }
            if (password !== confirmPassword) {
                setError('كلمة المرور وتأكيد كلمة المرور غير متطابقين.');
                return;
            }
        }

        const isEmailTaken = allUsers.some(
            u => u.email.toLowerCase() === email.trim().toLowerCase() && u.id !== userToEdit?.id
        );

        if (isEmailTaken) {
            setError('هذا البريد الإلكتروني مستخدم بالفعل.');
            return;
        }

        if (userToEdit) {
            const updatedData: User = {
                ...userToEdit,
                name: name.trim(),
                email: email.trim(),
                shopId
            };
            onSave(updatedData);
        } else {
            const newData: Omit<User, 'role' | 'isActive'> & { password: string } = {
                id: '', // Will be auto-generated by Firebase
                name: name.trim(),
                email: email.trim(),
                shopId,
                password: password.trim()
            };
            onSave(newData);
        }
    };
    
    if (!isOpen) return null;

    return (
        <div 
            className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50 transition-opacity duration-300"
            aria-modal="true"
            role="dialog"
        >
            <div className="bg-surface rounded-lg shadow-xl p-6 w-full max-w-md m-4 transform transition-all duration-300 scale-95 opacity-0 animate-fade-in-scale">
                <h2 className="text-2xl font-bold mb-6">{userToEdit ? 'تعديل مستخدم' : 'إضافة مستخدم جديد'}</h2>
                <form onSubmit={handleSubmit}>
                     {!userToEdit && (
                        <div className="bg-green-900/50 border border-green-700 text-green-200 text-sm rounded-lg p-3 mb-4">
                            <h4 className="font-bold">إضافة مستخدم جديد:</h4>
                            <p className="mt-1">سيتم إنشاء حساب جديد في Firebase تلقائياً وإرسال رابط التفعيل للبريد الإلكتروني.</p>
                        </div>
                    )}
                    <div className="space-y-4">
                        {!userToEdit && (
                            <>
                                <div>
                                    <label htmlFor="password" className="block text-sm font-medium text-text-secondary mb-1">كلمة المرور</label>
                                    <input
                                        type="password"
                                        id="password"
                                        value={password}
                                        onChange={(e) => setPassword(e.target.value)}
                                        placeholder="أدخل كلمة مرور قوية (6 أحرف على الأقل)"
                                        className="w-full bg-background border border-gray-600 rounded-md p-2 focus:ring-primary focus:border-primary"
                                        required
                                        minLength={6}
                                    />
                                </div>
                                <div>
                                    <label htmlFor="confirmPassword" className="block text-sm font-medium text-text-secondary mb-1">تأكيد كلمة المرور</label>
                                    <input
                                        type="password"
                                        id="confirmPassword"
                                        value={confirmPassword}
                                        onChange={(e) => setConfirmPassword(e.target.value)}
                                        placeholder="أعد إدخال كلمة المرور"
                                        className="w-full bg-background border border-gray-600 rounded-md p-2 focus:ring-primary focus:border-primary"
                                        required
                                    />
                                </div>
                            </>
                        )}
                        <div>
                            <label htmlFor="fullName" className="block text-sm font-medium text-text-secondary mb-1">الاسم الكامل</label>
                            <input
                                type="text"
                                id="fullName"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                className="w-full bg-background border border-gray-600 rounded-md p-2 focus:ring-primary focus:border-primary"
                                required
                            />
                        </div>
                        <div>
                            <label htmlFor="email" className="block text-sm font-medium text-text-secondary mb-1">البريد الإلكتروني (مطابق لحساب الدخول)</label>
                            <input
                                type="email"
                                id="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                className="w-full bg-background border border-gray-600 rounded-md p-2 focus:ring-primary focus:border-primary text-left"
                                required
                            />
                        </div>
                         <div>
                            <MobileSelect
                                label="المتجر المرتبط"
                                value={shopId}
                                onChange={(value) => setShopId(value)}
                                placeholder="-- اختر متجر --"
                                options={shops.map(shop => ({
                                    value: shop.id,
                                    label: shop.name
                                }))}
                            />
                        </div>
                         {error && <p className="text-red-500 text-sm text-center bg-red-500/10 p-2 rounded-md">{error}</p>}
                    </div>
                    <div className="mt-8 flex justify-end space-x-4 space-x-reverse">
                        <button
                            type="button"
                            onClick={onClose}
                            disabled={isLoading}
                            className="bg-gray-600 hover:bg-gray-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            إلغاء
                        </button>
                        <button
                            type="submit"
                            disabled={isLoading}
                            className="bg-primary hover:bg-primary-dark text-white font-bold py-2 px-4 rounded-lg transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {isLoading ? 'جاري المعالجة...' : (userToEdit ? 'حفظ التعديلات' : 'إضافة المستخدم')}
                        </button>
                    </div>
                </form>
            </div>
            <style>{`
                @keyframes fade-in-scale {
                    from { opacity: 0; transform: scale(0.95); }
                    to { opacity: 1; transform: scale(1); }
                }
                .animate-fade-in-scale { animation: fade-in-scale 0.2s ease-out forwards; }
            `}</style>
        </div>
    );
};

export default UserModal;
